.PHONY: clean All

All:
	@echo "----------Building project:[ IntializingVariables - Debug ]----------"
	@cd "IntializingVariables" && "$(MAKE)" -f  "IntializingVariables.mk"
clean:
	@echo "----------Cleaning project:[ IntializingVariables - Debug ]----------"
	@cd "IntializingVariables" && "$(MAKE)" -f  "IntializingVariables.mk" clean
